api/urls.py
from api.models import CourseResource, CategoryResource
from tastypie.api import Api
from django.urls import path, include

api = Api(api_name='v1')

api.register(CourseResource())
api.register(CategoryResource())

urlpatterns = [
    path('', include(api.urls), name='index'),
]

base/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('api/', include('api.urls'))
]

shop/urls.py
from django.urls import path
from . import views

app_name = "shop"
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:course_id>', views.singe_course, name='single_course')
]

api/models.py
from tastypie.resources import ModelResource
from shop.models import Category, Course
from tastypie.authorization import Authorization
from .authentication import CustomAuthentication


class CategoryResource(ModelResource):
    class Meta:
        queryset = Category.objects.all()
        resource_name = 'categories'
        allowed_methods = ['get']


class CourseResource(ModelResource):
    class Meta:
        queryset = Course.objects.all()
        resource_name = 'courses'
        allowed_methods = ['get', 'post', 'delete']
        excludes = ['reviews_qty', 'created_at']
        authentication = CustomAuthentication()
        authorization = Authorization()

    def hydrate(self, bundle):
        bundle.obj.category_id = bundle.data['category_id']
        return bundle

    def dehydrate(self, bundle):
        bundle.data['category_id'] = bundle.obj.category_id
        bundle.data['category'] = bundle.obj.category
        return bundle

    def dehydrate_title(self, bundle):
        return bundle.data['title'].upper()

shop/models.py
from django.utils import timezone
from django.db import models


class Category(models.Model):
    title = models.CharField(max_length=255)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


class Course(models.Model):
    title = models.CharField(max_length=300)
    price = models.FloatField()
    students_qty = models.IntegerField()
    reviews_qty = models.IntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

api/views.py
from django.shortcuts import render

# Create your views here.

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from .models import Course, Category


def index(request):
    courses = Course.objects.all()
    return render(request, 'shop/courses.html', {"courses": courses})


def singe_course(request, course_id):
    # OPTION1
    # try:
    #     course = Course.objects.get(pk=course_id)
    #     return render(request, 'single_course.html', {"course": course})
    # except Course.DoesNotExist:
    #     raise Http404()

    course = get_object_or_404(Course, pk=course_id)
    return render(request, 'shop/single_course.html', {"course": course})

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <title>{% block title %} {% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark">
      <div class="container">
        <a href='{% url "shop:index" %}' class="navbar-brand">Courses Shop</a>
        <span class="navbar-text">
          <a href="/admin/" class="navbar-brand me-2" target="_blank">Admin</a>
          <a href="/api/v1/" class="navbar-brand" target="_blank">Api</a>
        </span>
      </div>
    </nav>
    <main class="container">{% block content %} {% endblock %}</main>
  </body>
</html>

templates/shop/courses.html
{% extends 'base.html' %} {% block content %}

<table class="table mt-5 table-bordered table-striped table-hover">
  <thead class="table-dark">
    <tr>
      <th>Title</th>
      <th>Category</th>
      <th>Price</th>
      <th>Quantity</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for course in courses%}
    <tr>
      <td>
        <a href='{% url "shop:single_course" course.id%}'>{{course.title}}</a>
      </td>
      <td>{{course.category}}</td>
      <td>{{course.price}}</td>
      <td>{{course.students_qty}}</td>
      <td><button class="btn btn-primary">Buy</button></td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %} {% block title %} All courses {% endblock %}

templates/shop/single_course.html
{% extends 'base.html' %} {% block content %}

<h1>{{course.title}}</h1>
<h2>{{course.category}}</h2>
<p>Price: {{course.price}}</p>
<p>Students Quantity:{{course.students_qty}}</p>
<button class="btn btn-primary">Buy</button>

{% endblock %} {% block title %} Course {{course.title}} {% endblock %}